---
- name: "send command"
  hosts: routers
  connection: network_cli
  tasks: 
    - name: "sending command"
      cisco.ios.ios_facts:
        gather_subset: min

      register: cli_result

    - name: Print output
      debug:
        msg: "{{ cli_result }}"
        #msg: "{{ cli_result['parsed'] }}"
        