---
- name: "send command"
  hosts: routers
  connection: network_cli
  tasks: 
    - name: "sending command"
      cisco.ios.ios_facts:
        gather_subset:
          - '!all'
          - '!min'
        gather_network_resources: interfaces

      register: cli_result

    - name: Print output
      debug:
        #msg: "{{ cli_result }}"
        msg: "{{ cli_result['ansible_facts'] }}"
    
#https://docs.ansible.com/projects/ansible/latest/collections/cisco/ios/ios_facts_module.html#ansible-collections-cisco-ios-ios-facts-module
