all:
  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_network_os: ios
    ansible_connection: network_cli

  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.199.30
        R2:
          ansible_host: 192.168.199.31

    switches:
      hosts:
        Sw1:
          ansible_host: 192.168.199.40
        Sw2:
          ansible_host: 192.168.199.41
