---
- hosts: localhost
  tasks:
    - name: "Print"
      debug:
        msg: "{{ lookup('file', 'R1_config.txt') }}"


# It will finde the file with name "R1_config.txt" and print it.

# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook file.yaml 

# PLAY [localhost] *****************************************************************************************************************************************************************************************************

# TASK [Print] *********************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "host name R1\nint loop 1 \nip add 10.10.10.1 255.255.255.0"
# }

# PLAY RECAP ***********************************************************************************************************************************************************************************************************
# localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   