---
- hosts: localhost
  tasks:
    - name: "Print"
      debug:
        msg: "{{ lookup('file', 'R1_config.txt').splitlines() }}"


# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook file-lines.yaml 

# PLAY [localhost] *****************************************************************************************************************************************************************************************************

# TASK [Print] *********************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": [
#         "host name R1",
#         "int loop 1 ",
#         "ip add 10.10.10.1 255.255.255.0"
#     ]
# }

# PLAY RECAP ***********************************************************************************************************************************************************************************************************
# localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  