---
- hosts: localhost
  vars:
    IP_Addr:
      - 192.168.199.30
      - 192.168.199.31


  tasks:
    - name: print
      debug:
        msg: "The IP is: {{IP_Addr}}"
        #msg: "The IP is: {{ IP_Addr[1] }}"
        

# we can also refer to a member of a list like in python. If we dont specify the list member it will print all of the members.

# PLAY [localhost] *********************************************************************************************************************************************************************************************************************************

# TASK [print] *************************************************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "The IP is: 192.168.199.31"
# }

# without using the member number:
# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook variable-list.yaml 

# PLAY [localhost] *********************************************************************************************************************************************************************************************************************************

# TASK [print] *************************************************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "The IP is: ['192.168.199.30', '192.168.199.31']"
# }
