---
- hosts: localhost
  vars:
    IP_Addr:
      R1: 192.168.199.30
      R2: 192.168.199.31


  tasks:
    - name: print
      debug:
        #msg: "The IP is: {{IP_Addr}}"
        msg: "The IP is: {{ IP_Addr['R1'] }}"

# We can use the key in order to finde the value. 

# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook variable-dict.yaml 

# PLAY [localhost] *********************************************************************************************************************************************************************************************************************************

# TASK [print] *************************************************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "The IP is: {'R1': '192.168.199.30', 'R2': '192.168.199.31'}"
# }

# PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
# localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook variable-dict.yaml 

# PLAY [localhost] *********************************************************************************************************************************************************************************************************************************

# TASK [print] *************************************************************************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "The IP is: 192.168.199.30"
# }

# PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
# localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
