---
- hosts: localhost
  vars:
    IP_Addr:
      R1: 192.168.199.30
      R2: 192.168.199.31
      sw1: 192.168.199.40

  tasks:
    - name: print
      debug:
        msg: "{{ item.key }} - {{ item.value }}"
      with_dict: "{{ IP_Addr }}"


# If we want fo print key:value we can use with_dict

# saeed@saeed-ubuntu2:~/Desktop/Network-Automation/Ansible/Ansible_Playbook$ ansible-playbook with_dict.yaml

# PLAY [localhost] *****************************************************************************************************************************************************************************************************

# TASK [print] *********************************************************************************************************************************************************************************************************
# ok: [localhost] => (item={'key': 'R1', 'value': '192.168.199.30'}) => {
#     "msg": "R1 - 192.168.199.30"
# }
# ok: [localhost] => (item={'key': 'R2', 'value': '192.168.199.31'}) => {
#     "msg": "R2 - 192.168.199.31"
# }
# ok: [localhost] => (item={'key': 'sw1', 'value': '192.168.199.40'}) => {
#     "msg": "sw1 - 192.168.199.40"
# }

# PLAY RECAP ***********************************************************************************************************************************************************************************************************
# localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   